# Generated by Django 5.1.6 on 2025-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=750),
        ),
    ]
