# Generated by Django 5.1.6 on 2025-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_pay_timestamp_requestpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
