# Generated by Django 5.1.6 on 2025-04-05 00:15

import django.db.models.deletion
import payment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(default=payment.models.Currency, on_delete=django.db.models.deletion.CASCADE, to='payment.currency'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
