# Generated by Django 5.1.6 on 2025-04-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_profile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.ForeignKey(default='GBP', on_delete=django.db.models.deletion.CASCADE, to='payment.currency'),
        ),
    ]
